# Workflow for cmdfu CMake builds on multiple platforms and compilers
name: cmdfu CMake builds on multiple platforms

# Builds are triggered by:
# - Manual interaction (workflow_dispatch)
# - Push to main branch
# - Pull request to main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - c_compiler: gcc
            cpp_compiler: g++
          - c_compiler: clang
            cpp_compiler: clang++

    steps:
    - name: Checkout source
      uses: actions/checkout@v7

    - name: Set up CMake
      uses: lukka/get-cmake@v4.3.3
      with:
        cmakeVersion: "^3.25.0"

    - name: Configure CMake
      run: cmake -S . -B build -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}

    - name: Build
      run: cmake --build build

    # Store build artifact. The file name is created by using the OS type and compiler so we will have artifacts:
    # - cmdfu-Linux-gcc.zip
    # - cmdfu-Linux-clang.zip
    - name: Upload artifact
      uses: actions/upload-artifact@v7
      with:
        name: cmdfu-${{ runner.os }}-${{ matrix.c_compiler }}
        path: build/apps/cmdfu/cmdfu

  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v7

    - name: Set up MSYS2 (UCRT64)
      uses: msys2/setup-msys2@v2
      with:
        msystem: UCRT64
        update: false
        install: >-
          mingw-w64-ucrt-x86_64-gcc
          mingw-w64-ucrt-x86_64-cmake
          mingw-w64-ucrt-x86_64-ninja

    - name: Configure CMake
      shell: msys2 {0}
      run: >
        cmake -S . -B build -G "Ninja"
        -DCMAKE_BUILD_TYPE=Release
        -D LINUX_SUBSYSTEM_I2C=OFF
        -D LINUX_SUBSYSTEM_SPI=OFF
        -D LINUX_SUBSYSTEM_NETWORK=OFF
        -D LINUX_SUBSYSTEM_SERIAL=OFF
        -D WINDOWS_SUBSYSTEM_SERIAL=ON
        -DCMAKE_C_COMPILER=gcc
        -DCMAKE_CXX_COMPILER=g++

    - name: Build
      shell: msys2 {0}
      run: cmake --build build --target cmdfu

    # Store build artifact:
    # - cmdfu-Windows-gcc.zip
    - name: Upload artifact
      uses: actions/upload-artifact@v7
      with:
        name: cmdfu-${{ runner.os }}-gcc
        path: build/apps/cmdfu/cmdfu.exe
